name: dbt CI/CD

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  dbt-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dbt
        run: |
          pip install dbt-core dbt-snowflake dbt-utils

      - name: Install dependencies
        run: dbt deps

      - name: Debug environment
        run: dbt debug --target prod

      - name: Run dbt build
        run: dbt build --target prod

      - name: Run dbt tests
        run: dbt test --target prod

    env:
      DBT_USER: ${{ secrets.DBT_USER }}
      DBT_PASSWORD: ${{ secrets.DBT_PASSWORD }}
      DBT_ACCOUNT: ${{ secrets.DBT_ACCOUNT }}
      DBT_ROLE: ${{ secrets.DBT_ROLE }}
      DBT_WAREHOUSE: ${{ secrets.DBT_WAREHOUSE }}
      DBT_DATABASE: ${{ secrets.DBT_DATABASE }}
      DBT_SCHEMA: ${{ secrets.DBT_SCHEMA }}
